[package]
name = "silica-window"
version = "0.2.0"
edition = "2021"

[dependencies]
silica-gui = { path = "../silica-gui" }
silica-wgpu = { path = "../silica-wgpu" }
winit = "0.30"
env_logger = "0.11"
log = "0.4"
