[package]
name = "silica-wgpu"
version = "0.3.0"
edition = "2024"

[dependencies]
silica-color = { path = "../silica-color" }
log = "0.4"
wgpu = "25.0"
bytemuck = "1.23"
euclid = { version = "0.22", features = ["bytemuck"] }
pollster = "0.4"
