[package]
name = "silica-wgpu"
version = "0.2.0"
edition = "2021"

[dependencies]
silica-color = { path = "../silica-color" }
wgpu = "25.0"
bytemuck = "1.23"
pollster = "0.4"
euclid = { version = "0.22", features = ["bytemuck"] }
log = "0.4"
